package support;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
/**
 * 
 * @author         :Sathish
 * @since          :Sep 20, 2021
 * @filename       :Report.java
 * @version		   :
 * @description    :
 */
public class Report {
    private static Report report;
    static ExtentHtmlReporter testSummary;
    static ExtentReports extent;
    static String reportName;
    public static Report getInstance() {
        if (report == null) {
            report = new Report();
            testSummary = new ExtentHtmlReporter("TestSummaryReport.html");
            testSummary.config().setDocumentTitle("Report generated by Test Automation");
            testSummary.config().setReportName("Report generated by Test Automation");
            extent = new ExtentReports();
            extent.attachReporter(testSummary);
        }
        return report;
    }

    /**
     * 
     * Method Name : createNewReport
     * Return Type : ExtentTest
     * Author      : Sathish
     * Date		   : Sep 20, 2021
     * Description : Creation of new report for appending test results
     * @param testId
     * @param testName
     * @return
     */

    public synchronized ExtentTest createNewReport(String testId, String testName) {
        ExtentTest test;
        test = extent.createTest(testId + testName, testName);
        return test;
    }
    /**
     * 
     * Method Name : closeReport
     * Return Type : void
     * Author      : Sathish
     * Date		   : Sep 20, 2021
     * Description :
     */
    public synchronized void closeReport() {
        extent.flush();
    }


}